apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Release.Namespace }}
data:
  MYSQL_HOST: mysql-service
  MYSQL_PORT: {{ .Values.mysql.port | quote }}
  MYSQL_DATABASE: {{ .Values.config.mysqlDatabase | quote }}
  CHROMA_HOST: chroma-service
  CHROMA_PORT: {{ .Values.chromadb.port | quote }}
  API_ROOT_PATH: {{ .Values.config.apiRootPath | quote }}
  JWT_ALGORITHM: {{ .Values.config.jwtAlgorithm | quote }}
  JWT_EXPIRE_MINUTES: {{ .Values.config.jwtExpireMinutes | quote }}
