apiVersion: v1
kind: Service
metadata:
  name: chroma-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: chromadb
  ports:
    - port: {{ .Values.chromadb.port }}
      targetPort: 8000
