apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chromadb
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: chroma-service
  replicas: 1
  selector:
    matchLabels:
      app: chromadb
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
        - name: chromadb
          image: "{{ .Values.chromadb.image.repository }}:{{ .Values.chromadb.image.tag }}"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: {{ .Values.chromadb.storage }}
