import { useState } from "react";
import SessionItem from "./SessionItem";

function Sidebar({ sessions, activeSessionId, onSelect, onCreate, onRename, onDelete, user, onLogout, isLoading }) {
  const [mobileOpen, setMobileOpen] = useState(false);
  const content = <><div className="px-3 py-3 d-flex flex-column"><div className="d-flex align-items-center justify-content-between mb-4"><div className="d-flex align-items-center gap-2"><i className="bi-journal-text fs-2"/><span className="fw-semibold">Research Sidekick</span></div><button className="btn btn-sm d-lg-none" onClick={() => setMobileOpen(false)} aria-label="Close menu"><i className="bi-x-lg"/></button></div><button className="btn btn-outline-secondary btn-sm d-flex align-items-center gap-2" onClick={onCreate}><i className="bi-pencil-square"/>New Conversation</button></div><div className="px-3 flex-grow-1 overflow-auto"><p className="small fw-semibold mb-2">Conversations</p>{isLoading ? <div className="spinner-border spinner-border-sm"/> : sessions.length ? sessions.map((session) => <SessionItem key={session.id} session={session} activeSessionId={activeSessionId} onSelect={(id) => { onSelect(id); setMobileOpen(false); }} onRename={onRename} onDelete={onDelete}/>) : <p className="small text-secondary">No conversations yet.</p>}</div><div className="mt-auto px-3 py-3 border-top"><p className="small text-secondary text-truncate mb-2">{user.email}</p><button className="btn btn-outline-secondary btn-sm w-100" onClick={onLogout}>Logout</button></div></>;
  return <><div className="d-lg-none bg-white border-bottom p-2"><button className="btn btn-outline-secondary btn-sm" onClick={() => setMobileOpen(true)}><i className="bi-list me-2"/>Conversations</button></div><aside className="col-lg-2 d-none d-lg-flex flex-column bg-white border-end vh-100">{content}</aside>{mobileOpen && <><div className="mobile-sidebar-backdrop d-lg-none" onClick={() => setMobileOpen(false)}/><aside className="mobile-sidebar d-lg-none d-flex flex-column bg-white">{content}</aside></>}</>;
}
export default Sidebar;
